### DATA LOADING & EDA

In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe()
# df.describe(include='all')

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

### Feature Engineering

In [12]:
# labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
# df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

bins = [0, 25, 40, 60, 100]
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27        Adult
8   26        Adult
9   57  Middle-aged

In [14]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [ ]:
df = df.drop(columns=['promo_code_used'])

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

### SQL ANALYSIS

In [20]:
import duckdb

In [21]:
con = duckdb.connect()

In [22]:
con.register('user_shopping_data', df)

In [48]:
con.execute("""
select * 
from user_shopping_data 
limit 5 
            """).fetch_df()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [49]:
# total revenue generated by Male vs Female customers

con.execute("""
select gender, SUM(purchase_amount) as revenue
from user_shopping_data
group by gender
            """).fetch_df()

   gender   revenue
0    Male  157890.0
1  Female   75191.0

In [50]:
# customers used a discount but still spent more than the average purchase amount
con.execute("""
select customer_id, purchase_amount 
from user_shopping_data 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from user_shopping_data)
""").fetch_df()

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [51]:
# top 5 products with the highest average review rating
con.execute("""
select item_purchased, round(avg(cast(review_rating as float)),2) as "Average Product Rating"
from user_shopping_data
group by item_purchased
order by avg(review_rating) desc
limit 5
""").fetch_df()

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

In [52]:
# average Purchase Amounts between Standard and Express Shipping
con.execute("""
select shipping_type, round(avg(purchase_amount),2) avg_pur_amt
from user_shopping_data
where shipping_type in ('Standard','Express')
group by shipping_type
""").fetch_df()

  shipping_type  avg_pur_amt
0      Standard        58.46
1       Express        60.48

In [53]:
# average spend and total revenue - subscribers vs non-subscribers
con.execute("""
select subscription_status,
    count(customer_id) as total_customers,
    round(avg(purchase_amount),2) as avg_spend,
    round(sum(purchase_amount),2) as total_revenue
from user_shopping_data
group by subscription_status
order by total_revenue desc
""").fetch_df()

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [54]:
# Top 5 products with the highest percentage of purchases with discounts applied
con.execute("""
select item_purchased,
       round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from user_shopping_data
group by item_purchased
order by discount_rate desc
limit 5
""").fetch_df()

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [57]:
# New, Returning, and Loyal
con.execute("""
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment 
from user_shopping_data)

select customer_segment,count(*) as no_of_customers
from customer_type 
group by customer_segment
""").fetch_df()

  customer_segment  no_of_customers
0        Returning              701
1            Loyal             3116
2              New               83

In [60]:
# Top 3 most purchased products within each category
con.execute("""
with item_counts as (
    select category,
           item_purchased,
           count(customer_id) as total_orders,
           row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from user_shopping_data
    group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3
""").fetch_df()

    item_rank     category item_purchased  total_orders
0           1     Footwear        Sandals           160
1           2     Footwear          Shoes           150
2           3     Footwear       Sneakers           145
3           1  Accessories        Jewelry           171
4           2  Accessories     Sunglasses           161
5           3  Accessories           Belt           161
6           1    Outerwear         Jacket           163
7           2    Outerwear           Coat           161
8           1     Clothing          Pants           171
9           2     Clothing         Blouse           171
10          3     Clothing          Shirt           169

In [68]:
# repeat buyers (more than 5 previous purchases) also likely to subscribe
con.execute("""
select subscription_status, count(customer_id) as repeat_buyers
from user_shopping_data
where previous_purchases > 5
group by subscription_status
""").fetch_df()

  subscription_status  repeat_buyers
0                 Yes            958
1                  No           2518

In [65]:
# revenue contribution of each age group
con.execute("""
select age_group, 
    count(customer_id) as total_customers, 
    round(avg(purchase_amount), 2) as avg_pur_amt, 
    sum(purchase_amount) as total_revenue
from user_shopping_data
group by age_group
order by total_revenue desc
""").fetch_df()

     age_group  total_customers  avg_pur_amt  total_revenue
0  Middle-aged             1503        59.51        89445.0
1        Adult             1103        59.69        65842.0
2       Senior              723        59.70        43164.0
3  Young Adult              571        60.65        34630.0